CREATE PROFILE tienda_profile LIMIT
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 1/144
PASSWORD_LIFE_TIME 90
PASSWORD_GRACE_TIME 7;

CREATE USER tienda_admin IDENTIFIED BY "AdmTienda1234."
PROFILE tienda_profile;

GRANT CREATE SESSION TO tienda_admin;

GRANT CREATE TABLE TO tienda_admin;
GRANT CREATE VIEW TO tienda_admin;
GRANT CREATE PROCEDURE TO tienda_admin;
GRANT CREATE SEQUENCE TO tienda_admin;

ALTER USER tienda_admin QUOTA UNLIMITED ON DATA;

SELECT * FROM DUAL

