CREATE PROFILE tienda_profile LIMIT
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 1/144
PASSWORD_LIFE_TIME 90
PASSWORD_GRACE_TIME 7;

CREATE USER tienda_admin IDENTIFIED BY "AdmTienda1234."
PROFILE tienda_profile;

GRANT CREATE SESSION TO tienda_admin;

GRANT CREATE TABLE TO tienda_admin;
GRANT CREATE VIEW TO tienda_admin;
GRANT CREATE PROCEDURE TO tienda_admin;
GRANT CREATE SEQUENCE TO tienda_admin;

ALTER USER tienda_admin QUOTA UNLIMITED ON DATA;

SELECT * FROM DUAL

CREATE TABLE Rol (
    idRol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100)
);

CREATE TABLE Usuario (
    idUsuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idRol NUMBER,
    nombre VARCHAR2(100),
    apellido1 VARCHAR2(100),
    apellido2 VARCHAR2(100),
    correo VARCHAR2(150),
    telefono VARCHAR2(50),
    direccion VARCHAR2(200),
    password VARCHAR2(100),
    CONSTRAINT FK_usuario_rol 
        FOREIGN KEY (idRol) REFERENCES Rol(idRol)
);

CREATE TABLE Marca (
    idMarca NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100)
);


CREATE TABLE Categoria (
    idCategoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100)
);


CREATE TABLE Producto (
    idProducto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idMarca NUMBER,
    idCategoria NUMBER,
    nombre VARCHAR2(100),
    modelo VARCHAR2(100),
    descripcion VARCHAR2(200),

    CONSTRAINT FK_producto_marca
        FOREIGN KEY (idMarca) REFERENCES Marca(idMarca),

    CONSTRAINT FK_producto_categoria
        FOREIGN KEY (idCategoria) REFERENCES Categoria(idCategoria)
);


CREATE TABLE Proveedor (
    idProveedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    direccion VARCHAR2(200),
    telefono VARCHAR2(50),
    correo VARCHAR2(150)
);


CREATE TABLE Inventario (
    idInventario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idProducto NUMBER,
    idProveedor NUMBER,
    cantidadDisponible NUMBER,
    cantidadMinima NUMBER,
    costoUnitario NUMBER(10,2),
    ultimaFechaIngreso DATE,

    CONSTRAINT FK_inventario_producto
        FOREIGN KEY (idProducto) REFERENCES Producto(idProducto),

    CONSTRAINT FK_inventario_proveedor
        FOREIGN KEY (idProveedor) REFERENCES Proveedor(idProveedor)
);


CREATE TABLE Pedido (
    idPedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idUsuario NUMBER,
    fecha DATE,
    estado VARCHAR2(50),

    CONSTRAINT FK_pedido_usuario
        FOREIGN KEY (idUsuario) REFERENCES Usuario(idUsuario)
);


CREATE TABLE DetallePedido (
    idPedido NUMBER,
    idProducto NUMBER,
    cantidad NUMBER,
    precioUnitario NUMBER(10,2),

    CONSTRAINT PK_detallePedido 
        PRIMARY KEY (idPedido, idProducto),

    CONSTRAINT FK_detallePedido_pedido
        FOREIGN KEY (idPedido) REFERENCES Pedido(idPedido),

    CONSTRAINT FK_detallePedido_producto
        FOREIGN KEY (idProducto) REFERENCES Producto(idProducto)
);

CREATE TABLE Factura (
    idFactura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idPedido NUMBER,
    fecha DATE,
    subtotal NUMBER(10,2),
    impuesto NUMBER(10,2),
    total NUMBER(10,2),

    CONSTRAINT FK_factura_pedido
        FOREIGN KEY (idPedido) REFERENCES Pedido(idPedido)
);

CREATE TABLE MetodoPago (
    idMetodoPago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100)
);

CREATE TABLE Pago (
    idPago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idFactura NUMBER,
    idMetodoPago NUMBER,
    montoPagado NUMBER(10,2),
    estadoPago VARCHAR2(50),

    CONSTRAINT FK_pago_factura
        FOREIGN KEY (idFactura) REFERENCES Factura(idFactura),

    CONSTRAINT FK_pago_metodo
        FOREIGN KEY (idMetodoPago) REFERENCES MetodoPago(idMetodoPago)
);

INSERT INTO Rol (nombre) VALUES ('Administrador');
INSERT INTO Rol (nombre) VALUES ('Cliente');

INSERT INTO Usuario (idRol,nombre,apellido1,apellido2,correo,telefono,direccion,password)
VALUES (1,'Juan','Perez','Lopez','juan@gmail.com','88888888','San Jose','1234');
INSERT INTO Usuario (idRol,nombre,apellido1,apellido2,correo,telefono,direccion,password) 
VALUES (2,'Maria','Rodriguez','Soto','maria@gmail.com','87777777','Alajuela','1234');
INSERT INTO Usuario (idRol,nombre,apellido1,apellido2,correo,telefono,direccion,password) 
VALUES (2,'Carlos','Gomez','Diaz','carlos@gmail.com','86666666','Cartago','1234');

INSERT INTO Marca (nombre) VALUES ('Samsung');
INSERT INTO Marca (nombre) VALUES ('Apple');
INSERT INTO Marca (nombre) VALUES ('Sony');

INSERT INTO Categoria (nombre) VALUES ('Celulares');
INSERT INTO Categoria (nombre) VALUES ('Computadoras');
INSERT INTO Categoria (nombre) VALUES ('Accesorios');

INSERT INTO Producto (idMarca,idCategoria,nombre,modelo,descripcion) 
VALUES (1,1,'Galaxy S23','S23','Telefono Samsung');
INSERT INTO Producto (idMarca,idCategoria,nombre,modelo,descripcion) 
VALUES (2,1,'iPhone 14','A2890','Telefono Apple');
INSERT INTO Producto (idMarca,idCategoria,nombre,modelo,descripcion) 
VALUES (3,3,'Audifonos Sony','WH1000','Audifonos Inalambricos');

INSERT INTO Proveedor (nombre,direccion,telefono,correo) 
VALUES ('Tech Supply','San Jose','22223333','proveedor1@gmail.com');
INSERT INTO Proveedor (nombre,direccion,telefono,correo) 
VALUES ('Importaciones CR','Heredia','22224444','proveedor2@gmail.com');

INSERT INTO Inventario (idProducto,idProveedor,cantidadDisponible,cantidadMinima,costoUnitario,ultimaFechaIngreso) 
VALUES (1,1,50,10,500.00,SYSDATE);
INSERT INTO Inventario (idProducto,idProveedor,cantidadDisponible,cantidadMinima,costoUnitario,ultimaFechaIngreso) 
VALUES (2,1,30,5,900.00,SYSDATE);
INSERT INTO Inventario (idProducto,idProveedor,cantidadDisponible,cantidadMinima,costoUnitario,ultimaFechaIngreso) 
VALUES (3,2,80,20,200.00,SYSDATE);

INSERT INTO Pedido (idUsuario,fecha,estado) VALUES (2,SYSDATE,'En proceso');
INSERT INTO Pedido (idUsuario,fecha,estado) VALUES (3,SYSDATE,'Completado');

INSERT INTO DetallePedido VALUES (1,1,1,550.00);
INSERT INTO DetallePedido VALUES (1,3,2,220.00);
INSERT INTO DetallePedido VALUES (2,2,1,950.00);

INSERT INTO Factura (idPedido,fecha,subtotal,impuesto,total) 
VALUES (1,SYSDATE,990.00,128.70,1118.70);
INSERT INTO Factura (idPedido,fecha,subtotal,impuesto,total) 
VALUES (2,SYSDATE,950.00,123.50,1073.50);

INSERT INTO MetodoPago (nombre) VALUES ('Tarjeta');
INSERT INTO MetodoPago (nombre) VALUES ('Efectivo');
INSERT INTO MetodoPago (nombre) VALUES ('Transferencia');

INSERT INTO Pago (idFactura,idMetodoPago,montoPagado,estadoPago) VALUES (1,1,1118.70,'Pagado');
INSERT INTO Pago (idFactura,idMetodoPago,montoPagado,estadoPago) VALUES (2,3,1073.50,'Pagado');

COMMIT;

SELECT * FROM Usuario;

SELECT * FROM Producto;

SELECT * FROM Inventario;

SELECT * FROM Pedido;

SELECT * FROM Factura;



